//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentOrderApp.PaymentOrderReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentOrderDTO", Namespace="http://schemas.datacontract.org/2004/07/PaymentOrderModel")]
    [System.SerializableAttribute()]
    public partial class PaymentOrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FinancialInstituionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OriginatorConversationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrincipalActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecepientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecepientPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemitterAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitterIdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemitterIdTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemitterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemitterPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RouteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceOfFundsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SystemTraceAuditNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ccy {
            get {
                return this.CcyField;
            }
            set {
                if ((object.ReferenceEquals(this.CcyField, value) != true)) {
                    this.CcyField = value;
                    this.RaisePropertyChanged("Ccy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FinancialInstituion {
            get {
                return this.FinancialInstituionField;
            }
            set {
                if ((object.ReferenceEquals(this.FinancialInstituionField, value) != true)) {
                    this.FinancialInstituionField = value;
                    this.RaisePropertyChanged("FinancialInstituion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OriginatorConversationId {
            get {
                return this.OriginatorConversationIdField;
            }
            set {
                if ((this.OriginatorConversationIdField.Equals(value) != true)) {
                    this.OriginatorConversationIdField = value;
                    this.RaisePropertyChanged("OriginatorConversationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryAccountNumber {
            get {
                return this.PrimaryAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryAccountNumberField, value) != true)) {
                    this.PrimaryAccountNumberField = value;
                    this.RaisePropertyChanged("PrimaryAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrincipalActivity {
            get {
                return this.PrincipalActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.PrincipalActivityField, value) != true)) {
                    this.PrincipalActivityField = value;
                    this.RaisePropertyChanged("PrincipalActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecepientName {
            get {
                return this.RecepientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RecepientNameField, value) != true)) {
                    this.RecepientNameField = value;
                    this.RaisePropertyChanged("RecepientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecepientPhoneNumber {
            get {
                return this.RecepientPhoneNumberField;
            }
            set {
                if ((this.RecepientPhoneNumberField.Equals(value) != true)) {
                    this.RecepientPhoneNumberField = value;
                    this.RaisePropertyChanged("RecepientPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemitterAddress {
            get {
                return this.RemitterAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitterAddressField, value) != true)) {
                    this.RemitterAddressField = value;
                    this.RaisePropertyChanged("RemitterAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitterIdNumber {
            get {
                return this.RemitterIdNumberField;
            }
            set {
                if ((this.RemitterIdNumberField.Equals(value) != true)) {
                    this.RemitterIdNumberField = value;
                    this.RaisePropertyChanged("RemitterIdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemitterIdType {
            get {
                return this.RemitterIdTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitterIdTypeField, value) != true)) {
                    this.RemitterIdTypeField = value;
                    this.RaisePropertyChanged("RemitterIdType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RemitterName {
            get {
                return this.RemitterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RemitterNameField, value) != true)) {
                    this.RemitterNameField = value;
                    this.RaisePropertyChanged("RemitterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemitterPhoneNumber {
            get {
                return this.RemitterPhoneNumberField;
            }
            set {
                if ((this.RemitterPhoneNumberField.Equals(value) != true)) {
                    this.RemitterPhoneNumberField = value;
                    this.RaisePropertyChanged("RemitterPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RouteId {
            get {
                return this.RouteIdField;
            }
            set {
                if ((this.RouteIdField.Equals(value) != true)) {
                    this.RouteIdField = value;
                    this.RaisePropertyChanged("RouteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceOfFunds {
            get {
                return this.SourceOfFundsField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceOfFundsField, value) != true)) {
                    this.SourceOfFundsField = value;
                    this.RaisePropertyChanged("SourceOfFunds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SystemTraceAuditNumber {
            get {
                return this.SystemTraceAuditNumberField;
            }
            set {
                if ((this.SystemTraceAuditNumberField.Equals(value) != true)) {
                    this.SystemTraceAuditNumberField = value;
                    this.RaisePropertyChanged("SystemTraceAuditNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentOrderReference.IPaymentOrderService")]
    public interface IPaymentOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/GetPaymentOrder", ReplyAction="http://tempuri.org/IPaymentOrderService/GetPaymentOrderResponse")]
        PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO[] GetPaymentOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/GetPaymentOrder", ReplyAction="http://tempuri.org/IPaymentOrderService/GetPaymentOrderResponse")]
        System.Threading.Tasks.Task<PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO[]> GetPaymentOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Get", ReplyAction="http://tempuri.org/IPaymentOrderService/GetResponse")]
        PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO Get(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Get", ReplyAction="http://tempuri.org/IPaymentOrderService/GetResponse")]
        System.Threading.Tasks.Task<PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO> GetAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Add", ReplyAction="http://tempuri.org/IPaymentOrderService/AddResponse")]
        void Add(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Add", ReplyAction="http://tempuri.org/IPaymentOrderService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Remove", ReplyAction="http://tempuri.org/IPaymentOrderService/RemoveResponse")]
        void Remove(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Remove", ReplyAction="http://tempuri.org/IPaymentOrderService/RemoveResponse")]
        System.Threading.Tasks.Task RemoveAsync(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Update", ReplyAction="http://tempuri.org/IPaymentOrderService/UpdateResponse")]
        void Update(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentOrderService/Update", ReplyAction="http://tempuri.org/IPaymentOrderService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentOrderServiceChannel : PaymentOrderApp.PaymentOrderReference.IPaymentOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentOrderServiceClient : System.ServiceModel.ClientBase<PaymentOrderApp.PaymentOrderReference.IPaymentOrderService>, PaymentOrderApp.PaymentOrderReference.IPaymentOrderService {
        
        public PaymentOrderServiceClient() {
        }
        
        public PaymentOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO[] GetPaymentOrder() {
            return base.Channel.GetPaymentOrder();
        }
        
        public System.Threading.Tasks.Task<PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO[]> GetPaymentOrderAsync() {
            return base.Channel.GetPaymentOrderAsync();
        }
        
        public PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO Get(int Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO> GetAsync(int Id) {
            return base.Channel.GetAsync(Id);
        }
        
        public void Add(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity) {
            base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task AddAsync(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public void Remove(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity) {
            base.Channel.Remove(entity);
        }
        
        public System.Threading.Tasks.Task RemoveAsync(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity) {
            return base.Channel.RemoveAsync(entity);
        }
        
        public void Update(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(PaymentOrderApp.PaymentOrderReference.PaymentOrderDTO entity) {
            return base.Channel.UpdateAsync(entity);
        }
    }
}
